// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/pack.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/pack.go -destination=internal/mocks/pack.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/2yuri/pack-calculator/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPackRepository is a mock of PackRepository interface.
type MockPackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPackRepositoryMockRecorder
	isgomock struct{}
}

// MockPackRepositoryMockRecorder is the mock recorder for MockPackRepository.
type MockPackRepositoryMockRecorder struct {
	mock *MockPackRepository
}

// NewMockPackRepository creates a new mock instance.
func NewMockPackRepository(ctrl *gomock.Controller) *MockPackRepository {
	mock := &MockPackRepository{ctrl: ctrl}
	mock.recorder = &MockPackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackRepository) EXPECT() *MockPackRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPackRepository) Create(ctx context.Context, productID, size int) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, productID, size)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPackRepositoryMockRecorder) Create(ctx, productID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPackRepository)(nil).Create), ctx, productID, size)
}

// CreateBatch mocks base method.
func (m *MockPackRepository) CreateBatch(ctx context.Context, productID int, sizes []int) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, productID, sizes)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPackRepositoryMockRecorder) CreateBatch(ctx, productID, sizes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPackRepository)(nil).CreateBatch), ctx, productID, sizes)
}

// Delete mocks base method.
func (m *MockPackRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPackRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPackRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockPackRepository) GetAll(ctx context.Context) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPackRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPackRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockPackRepository) GetByID(ctx context.Context, id int) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPackRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPackRepository)(nil).GetByID), ctx, id)
}

// GetByProductID mocks base method.
func (m *MockPackRepository) GetByProductID(ctx context.Context, productID int) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductID", ctx, productID)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductID indicates an expected call of GetByProductID.
func (mr *MockPackRepositoryMockRecorder) GetByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductID", reflect.TypeOf((*MockPackRepository)(nil).GetByProductID), ctx, productID)
}

// Update mocks base method.
func (m *MockPackRepository) Update(ctx context.Context, id, size int) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, size)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPackRepositoryMockRecorder) Update(ctx, id, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPackRepository)(nil).Update), ctx, id, size)
}

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// GetPacksByProductIDs mocks base method.
func (m *MockCacheRepository) GetPacksByProductIDs(ctx context.Context, productIDs []int) ([]*domain.ProductPacks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPacksByProductIDs", ctx, productIDs)
	ret0, _ := ret[0].([]*domain.ProductPacks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPacksByProductIDs indicates an expected call of GetPacksByProductIDs.
func (mr *MockCacheRepositoryMockRecorder) GetPacksByProductIDs(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPacksByProductIDs", reflect.TypeOf((*MockCacheRepository)(nil).GetPacksByProductIDs), ctx, productIDs)
}

// Invalidate mocks base method.
func (m *MockCacheRepository) Invalidate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockCacheRepositoryMockRecorder) Invalidate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockCacheRepository)(nil).Invalidate), ctx)
}

// RemovePack mocks base method.
func (m *MockCacheRepository) RemovePack(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePack", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePack indicates an expected call of RemovePack.
func (mr *MockCacheRepositoryMockRecorder) RemovePack(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePack", reflect.TypeOf((*MockCacheRepository)(nil).RemovePack), ctx, id)
}

// SetPack mocks base method.
func (m *MockCacheRepository) SetPack(ctx context.Context, pack *domain.Pack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPack", ctx, pack)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPack indicates an expected call of SetPack.
func (mr *MockCacheRepositoryMockRecorder) SetPack(ctx, pack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPack", reflect.TypeOf((*MockCacheRepository)(nil).SetPack), ctx, pack)
}

// SetPacks mocks base method.
func (m *MockCacheRepository) SetPacks(ctx context.Context, packs []*domain.Pack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPacks", ctx, packs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPacks indicates an expected call of SetPacks.
func (mr *MockCacheRepositoryMockRecorder) SetPacks(ctx, packs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPacks", reflect.TypeOf((*MockCacheRepository)(nil).SetPacks), ctx, packs)
}

// MockPackService is a mock of PackService interface.
type MockPackService struct {
	ctrl     *gomock.Controller
	recorder *MockPackServiceMockRecorder
	isgomock struct{}
}

// MockPackServiceMockRecorder is the mock recorder for MockPackService.
type MockPackServiceMockRecorder struct {
	mock *MockPackService
}

// NewMockPackService creates a new mock instance.
func NewMockPackService(ctrl *gomock.Controller) *MockPackService {
	mock := &MockPackService{ctrl: ctrl}
	mock.recorder = &MockPackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackService) EXPECT() *MockPackServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPackService) Create(ctx context.Context, productID, size int) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, productID, size)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPackServiceMockRecorder) Create(ctx, productID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPackService)(nil).Create), ctx, productID, size)
}

// CreateBatch mocks base method.
func (m *MockPackService) CreateBatch(ctx context.Context, productID int, sizes []int) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, productID, sizes)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockPackServiceMockRecorder) CreateBatch(ctx, productID, sizes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockPackService)(nil).CreateBatch), ctx, productID, sizes)
}

// Delete mocks base method.
func (m *MockPackService) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPackServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPackService)(nil).Delete), ctx, id)
}

// GetByProductID mocks base method.
func (m *MockPackService) GetByProductID(ctx context.Context, productID int) ([]*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductID", ctx, productID)
	ret0, _ := ret[0].([]*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductID indicates an expected call of GetByProductID.
func (mr *MockPackServiceMockRecorder) GetByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductID", reflect.TypeOf((*MockPackService)(nil).GetByProductID), ctx, productID)
}

// Update mocks base method.
func (m *MockPackService) Update(ctx context.Context, id, size int) (*domain.Pack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, size)
	ret0, _ := ret[0].(*domain.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPackServiceMockRecorder) Update(ctx, id, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPackService)(nil).Update), ctx, id, size)
}
